name: 'Stale issues and PR'
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: harupy/stale@mlflow-stale-bot
        with:
          stale-issue-message: 'This issue is stale because it has been open 1 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 1 days with no activity.'
          days-before-stale: 0
          days-before-close: 0
          start-date: '2022-06-16T00:00:00Z'
          # Never stale/close pull requests
          days-before-pr-stale: -1
          days-before-pr-close: -1
          days-since-issue-created: 0
          days-since-last-comment-created: 0
